USE [master]
GO

/****** Object:  Database [Contacts]    Script Date: 2016-02-15 15:13:21 ******/
CREATE DATABASE [Contacts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contacts', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Contacts.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Contacts_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Contacts_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Contacts] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Contacts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Contacts] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Contacts] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Contacts] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Contacts] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Contacts] SET ARITHABORT OFF 
GO

ALTER DATABASE [Contacts] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Contacts] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Contacts] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Contacts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Contacts] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Contacts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Contacts] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Contacts] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Contacts] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Contacts] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Contacts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Contacts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Contacts] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Contacts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Contacts] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Contacts] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Contacts] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Contacts] SET RECOVERY FULL 
GO

ALTER DATABASE [Contacts] SET  MULTI_USER 
GO

ALTER DATABASE [Contacts] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Contacts] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Contacts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Contacts] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Contacts] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Contacts] SET  READ_WRITE 
GO

